[qbittorrent]
addr       = "http://seedbox:8080" # qbittorrent webui-api hostname/ip
# login      = "admin"                  # qbittorrent webui-api user
# password   = "adminadmin"              # qbittorrent webui-api password
